FROM alpine:latest

LABEL org.opencontainers.image.authors="Sokratis Ioannidis"
LABEL version="0.1"
LABEL description="Docker image with helm tools for using in a CI/CD"
LABEL src=https://github.com/sokratis1988/docker-images

#ENV
ARG HELM_VERSION
ENV HELM=${HELM_VERSION}
ARG KUBELOGIN_VERSION=0.0.34
ENV KUBELOGIN=${KUBELOGIN_VERSION}
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# Upgrade OS
RUN apk add -U -q --no-cache git curl wget gettext
RUN apk upgrade

# Install helm
RUN wget --quiet https://get.helm.sh/helm-$HELM-linux-amd64.tar.gz
RUN tar -zxvf helm-$HELM-linux-amd64.tar.gz
RUN mv linux-amd64/helm /usr/bin/helm && chmod +x /usr/bin/helm
RUN rm -r linux-amd64/ helm-$HELM-linux-amd64.tar.gz

# Install kubelogin
RUN wget --quiet https://github.com/Azure/kubelogin/releases/download/v$KUBELOGIN/kubelogin-linux-amd64.zip
RUN unzip kubelogin-linux-amd64.zip
RUN ls -la
RUN mv bin/linux_amd64/kubelogin /usr/bin/kubelogin && chmod +x /usr/bin/kubelogin
RUN rm -r bin/linux_amd64 kubelogin-linux-amd64.zip

# Install Plugins
RUN helm plugin install https://github.com/chartmuseum/helm-push

ENTRYPOINT [ "helm" ]
CMD ["--help"]