name: ci

on:
  push:
    branches:
      - "main"
      - "dev"
  schedule: 
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      ansible-versions: ${{ steps.get-releases.outputs.ansible-versions }}
    steps:
      - uses: actions/checkout@v3

      - name: Get releases
        id: get-releases
        run: |
          chmod +x ./prepare.sh
          ANSIBLE_VERSIONS=$(./prepare.sh --pypi-project ansible --latest --exclude-release-candidates)
          #echo "ansible-versions=$(echo \"$ansible-versions\")" >> $GITHUB_OUTPUT
          echo "::set-output name=ansible-versions::$ANSIBLE_VERSIONS"

  build:
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible-version: ${{ fromJson(needs.get-versions.outputs.ansible-versions) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Prepare Ansible Version
        run: echo "ANSIBLE_VERSION=${{ matrix.ansible-version }}" | sed 's/v//g' > $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ansible/python-slim/
          file: ansible/python-slim/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sokratis1988/ansible:${{ env.ANSIBLE_VERSION }}
            ghcr.io/sokratis1988/ansible:${{ env.ANSIBLE_VERSION }}
          build-args: |
            "ANSIBLE_VERSION=${{ matrix.ansible-version }}"