name: ci

on:
  push:
    branches:
      - "main"
      - "dev"
  schedule: 
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      helm-versions: ${{ steps.get-helm-releases.outputs.helm-versions }}
      #helm-push-versions: ${{ steps.get-helm-push-releases.outputs.helm-push-versions }}
    steps:
      - uses: actions/checkout@v3

      - name: Get helm releases
        id: get-helm-releases
        run: |
          chmod +x ./prepare.sh
          HELM_VERSIONS=$(./prepare.sh --github-repo helm --github-project helm --per-page 30)
          #echo "helm-versions=$(echo \"$HELM-VERSIONS\")" >> $GITHUB_OUTPUT
          echo "::set-output name=helm-versions::$HELM_VERSIONS"

      - name: Get helm-push releases
        id: get-helm-push-releases
        run: |
          chmod +x ./prepare.sh
          PUSH_VERSIONS=$(./prepare.sh --github-repo chartmuseum --github-project helm-push --per-page 30)
          #echo "helm-push-versions=$(echo \"$PUSH-VERSIONS\")" >> $GITHUB_OUTPUT
          echo "::set-output name=helm-push-versions::$PUSH_VERSIONS"

  build:
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm-version: ${{ fromJson(needs.get-versions.outputs.helm-versions) }}
        #helm-push-version: ${{ fromJson(needs.get-versions.outputs.helm-push-versions) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Prepare Helm Version
        run: echo "HELM_VERSION=${{ matrix.helm-version }}" | sed 's/v//g' > $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: helm/alpine/
          file: helm/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sokratis1988/helm:${{ env.HELM_VERSION }}
            ghcr.io/sokratis1988/helm:${{ env.HELM_VERSION }}
          build-args: |
            "HELM_VERSION=${{ matrix.helm-version }}"
      -
        name: Build and push with kubelogin
        uses: docker/build-push-action@v3
        with:
          context: helm/alpine/
          file: helm/alpine/Dockerfile-kubelogin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sokratis1988/helm:${{ env.HELM_VERSION }}-kubelogin
            ghcr.io/sokratis1988/helm:${{ env.HELM_VERSION }}-kubelogin
          build-args: |
            "HELM_VERSION=${{ matrix.helm-version }}"
    