name: ci

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Fetch Helm Versions
        id: fetch-versions
        run: |
          chmod +x ./prepare.sh
          VERSIONS=$(./prepare.sh --github-repo helm --github-project helm)
          echo "::set-output name=versions::$(echo \"$VERSIONS\" | jq -R -s -c 'split("\n")[:-1]')"
      -
        name: Fetch Latest Helm Version
        id: fetch-latest-version
        run: |
          chmod +x ./prepare.sh
          VERSIONS=$(./prepare.sh --github-repo helm --github-project helm --latest)
          echo "::set-output name=versions::$(echo \"$VERSIONS\" | jq -R -s -c 'split("\n")[:-1]')"
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: helm/alpine/
          file: helm/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sokratis1988/helm:${{ matrix.version }}
            ghcr.io/sokratis1988:${{ matrix.version }}
          build-args: HELM_VERSION=${{ matrix.version }} BUILD_VERSION="00001"
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: helm/alpine/
          file: helm/alpine/Dockerfile-kubelogin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sokratis1988/helm:latest-kubelogin
            sokratis1988/helm:3.13.1-kubelogin
            ghcr.io/sokratis1988/helm:latest-kubelogin
            ghcr.io/sokratis1988/helm:3.13.1-kubelogin
    strategy:
      matrix:
        version: ${{fromJson(steps.fetch-versions.outputs.versions)}}
      fail-fast: false