name: ci

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v3

      - name: Get release versions
        id: get-versions
        run: |
          chmod +x ./prepare.sh
          VERSIONS=$(./prepare.sh --github-repo helm --github-project helm)
          echo "versions=$(echo \"$VERSIONS\" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          echo "GITHUB_OUTPUT: " $GITHUB_OUTPUT
          #echo "::set-output name=versions::$(echo \"$VERSIONS\" | jq -R -s -c 'split("\n")[:-1]')"
          #echo $VERSIONS


  build:
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ needs.get-versions.outputs.versions }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: helm/alpine/
          file: helm/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sokratis1988/helm:${{ matrix.version }}
            ghcr.io/sokratis1988:${{ matrix.version }}
          build-args: HELM_VERSION=${{ matrix.version }} BUILD_VERSION="00001"
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: helm/alpine/
          file: helm/alpine/Dockerfile-kubelogin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sokratis1988/helm:latest-kubelogin
            sokratis1988/helm:3.13.1-kubelogin
            ghcr.io/sokratis1988/helm:latest-kubelogin
            ghcr.io/sokratis1988/helm:3.13.1-kubelogin
    